### ISSUE TITLE
请问一下 是否支持 根据接收到的数据 返回数据

### ISSUE THREAD

**Issue by River00Demon** [ChuChencheng/wsmock-js#2]
`receiver (data) {
    if (data.action === 'heartbeat') {
      // 在这里发送数据
    }
  }`
现在我是在 receiver里面把接收到的data赋值给了this.receiveData然后再sender里面再根据这个receiveData来决定输出

**Comment by ChuChencheng** [comment]
目前没有直接支持，但是 `receiver` 跟 `sender` 绑定的 `this` 是同一个，应该可以把接收的数据挂在 `this` 上，例如：

```javascript
const mock = {
  receiver (data) {
    this.receivedData = data
  }
  sender () {
    if (this.receivedData) {
      if (this.receivedData.action === 'heartbeat') {
        this.response = 'xxx'
      }
    }
  }
}
```

我这边没有尝试过，你可以试试

**Comment by River00Demon** [comment]
好的 谢谢
